### ISSUE TITLE
No module named '_tkinter'

### ISSUE THREAD

**Issue by fsoc106** [OSTEsayed/OSTE-Meta-Scan#1]
Hello, I have a bug i installed all depencie but I have this problem when I start Metascan.py

Traceback (most recent call last):
  File "/workspace/OSTE-Meta-Scan/OSTEscaner/Metascan.py", line 1, in <module>
    import tkinter
  File "/root/.pyenv/versions/3.11.7/lib/python3.11/tkinter/__init__.py", line 38, in <module>
    import _tkinter # If this fails your Python may not be configured for Tk
    ^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named '_tkinter'

**Comment by MathFrenchToast** [comment]
Hi, on a brand new kali (used in WSL)

You can follow this setup:
To install all the required packages
`sudo apt install python3-pip python3-tk zaproxy  wapiti skipfish  nikto nuclei -y `
tk (aka tkinter) is provided by `python3-tk `package

then create a requirements.txt file containing:
``` 
tk
customtkinter
zaproxy
jinja2
# PIL
pillow
matplotlib
beautifulsoup4
pprintpp
```

and run: `pip install -r requirements.txt`  to install all the require library at once.
you can use a python env if you want.

I'm working on a docker file also, and will propose a PR when testing is completed (just discover the repo today).

**Comment by OSTEsayed** [comment]
-Fsoc106 this error is a issue related to your environmental configuration and tkinter lib not part of the oste issue. Make sure to install tkinter and costumetkinter using the pip3 command. To make sure whather it is installed or no use the command pip3 freeze and see if it's there. 

-mathfrenchtoast nice instructions and am looking forward for your contribution. Making a docker env would be a really nice add thank you.
